// WEEK 1 EQUALS THIS WEEK

var sgData = [
	{
		categories: [],
		title: '[0323 Full Time] Orientation',
		description: 'Come join.',
		day: 'Monday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    
    {
		categories: [],
		title: '[0323 Full Time] Lab Walkthrough - Methods & Arguments Lab and Methods & Default Arguments Lab',
		description: 'Come join.',
		day: 'Monday',
		time: '3:00 pm',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Lab Walkthrough - If Statements Lab && Ternary Operators and Statement Modifiers',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Tuesday',
		time: '3:00 pm',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Live Lecture - Arrays',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Lab Walkthrough - My Each, My Collect, My all, My find lab',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Thursday',
		time: '3:00 pm',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Pair Programming Demo + Practice',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '3:00 pm',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
	},
    //start Week 2
	{
		categories: [],
		title: '[0323 Full Time] Live Lecture: Intro To OO Ruby',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',  
    },
    {
		categories: [],
		title: '[0323 Full Time] Live Lecture Object Initialization & Object Properties',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',  
    },
    {
		categories: [],
		title: '[0323 Full Time] Live Lecture: Object Self & Class Variables',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',  
    },
    {
		categories: [],
		title: '[0323 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',   
	}
];
