// WEEK 1 EQUALS THIS WEEK

var sgData = [
	{
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to React & Props',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - React State & Events',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - React Forms',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - React Lifecycle Methods',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Presentational vs Container Components',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to Client Side Routing',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to Redux',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Hot Potato Lab Walkthrough - Cooking with Redux',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Async Redux',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    }
];

