// WEEK 1 EQUALS THIS WEEK
var sgDataProjectWeek = [
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
    description: 'Come join.',
		day: 'Monday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
      categories: [],
      title: '[0908 Full Time] Open Office Hours',
      description: 'Come join.',
      day: 'Monday',
      time: '3:00 pm',
      weekToStart: 2,
      weekToEnd: 2,
      zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
      categories: [],
      title: '[0908 Full Time] Open Office Hours',
      description: 'Come join.',
      day: 'Tuesday',
      time: '3:00 pm',
      weekToStart: 2,
      weekToEnd: 2,
      zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
      categories: [],
      title: '[0908 Full Time] Open Office Hours',
      description: 'Come join.',
      day: 'Wednesday',
      time: '3:00 pm',
      weekToStart: 2,
      weekToEnd: 2,
      zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
      categories: [],
      title: '[0908 Full Time] Open Office Hours',
      description: 'Come join.',
      day: 'Thursday',
      time: '3:00 pm',
      weekToStart: 2,
      weekToEnd: 2,
      zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/91867186499?pwd=QlgzTEJLLzJPeHdZbW1mTllSc0ZTUT09',
    },
    {
      categories: [],
      title: '[0908 Full Time] Open Office Hours',
      description: 'Come join.',
      day: 'Friday',
      time: '3:00 pm',
      weekToStart: 2,
      weekToEnd: 2,
      zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
      
    }
];