// WEEK 1 EQUALS THIS WEEK

var sgData = [
	{
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to SQL',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Pairing - SQL Queries Bootcamp',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Build an ORM from Scratch',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 1,
		weekToEnd: 1,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to ActiveRecord',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - ActiveRecord & Associations',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Sinatra Basics',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 6,
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Sinatra REST, MVC, and Forms',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Sinatra CRUD',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - User Authentication in Sinatra',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    }
];
