// WEEK 1 EQUALS THIS WEEK

var sgData = [
	{
		categories: [],
		title: '[0908 Full Time] Orientation',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
        title: '[0908 Full Time] Open Office Hours',
        description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Pair Programming Demo + Practice',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/91867186499?pwd=QlgzTEJLLzJPeHdZbW1mTllSc0ZTUT09',
    },
    //start Week 2
	{
		categories: [],
		title: '[0323 Full Time] Live Lecture: Intro To OO Ruby',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Live Lecture Object Initialization & Object Properties',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Live Lecture: Object Self & Class Variables',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/96807146556?pwd=YnZod3ZpM0NSSVZLczZYNVlRaFAyQT09',
    },
    {
		categories: [],
		title: '[0323 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/91867186499?pwd=QlgzTEJLLzJPeHdZbW1mTllSc0ZTUT09',   
	}
];
