// WEEK 1 EQUALS THIS WEEK

var sgData = [
	{
		categories: [],
		title: '[0908 Full Time] Live Lecture - Intro to DOM and DOM Manipulation',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - JavaScript Fundamentals',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - JavaScript Events',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 2,
		weekToEnd: 2,
		zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Using Fetch',
		description: 'Come join.',
		day: 'Monday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Building a Rails API',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Putting it all Together (update/destroy; JS Array methods)',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 3,
		weekToEnd: 3,
		zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - ES6 Deep Dive (Arrow Functions, Variable Declaration, Destructuring, Object Assign)',
		description: 'Come join.',
		day: 'Tuesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - Object Oriented JS',
		description: 'Come join.',
		day: 'Wednesday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Live Lecture - JS Prototypal Inheritance',
		description: 'Come join.',
		day: 'Thursday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/93581559641?pwd=R09wZThzTGtUMmY5ck84OTkwZFhIdz09',
    },
    {
		categories: [],
		title: '[0908 Full Time] Open Office Hours',
		description: 'Come join.',
		day: 'Friday',
		time: '11:00 am',
		weekToStart: 4,
		weekToEnd: 4,
		zoom: 'https://flatironschool.zoom.us/j/4666475163?pwd=bWp5VFJYdVg3ckczczRmZkllbkhSdz09',
    }
];




